"use client";
import { Inter } from "next/font/google";
import Header from "./_components/Header/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { SWRConfig } from "swr";
import { CartContext } from "./_Context/cartContext";
import { BookMarkContext } from "./_Context/bookMarkContext";
import "./globals.css";
import Footer from "./_components/Footer/Footer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  const [booked, setBooked] = useState([]);

  return (
    <ClerkProvider>
      <SWRConfig
        value={{ fetcher: (url) => fetch(url).then((res) => res.json()) }}
      >
        <CartContext.Provider value={{ cart, setCart }}>
          <BookMarkContext.Provider value={{ booked, setBooked }}>
            <html lang="en">
              <body className={inter.className}>
                <Header />
                {children}
                <Footer />
              </body>
            </html>
          </BookMarkContext.Provider>
        </CartContext.Provider>
      </SWRConfig>
    </ClerkProvider>
  );
}
